### ISSUE TITLE
error in check mk plugin if backup client is removed from server

### ISSUE THREAD

**Issue by yennor** [edvler/check_mk-urbackup-check#1]
If you remove a backup client from the urbackup server. The urbackup check plugin of shows an error (instead of just backup not found. or similar). It's a minimal annoyance, nothing grave ;-).
it shows:
error occured in check plugin. Please post a issue on inlcuding the output of the agent plugin /usr/lib/check_mk_agent/plugins/urbackup-check.
The plugin runs perfectly on the client (urbackup server). So I guess the error must be on the server side.
Couldn't find the aprorpiate log. sorry. but it should be easy enough to reproduce :-)

**Comment by edvler** [comment]
Should be solved now

**Comment by edvler** [comment]
Should be solved now
