### ISSUE TITLE
wrong url for issues

### ISSUE THREAD

**Issue by yennor** [edvler/check_mk-urbackup-check#2]
I only report that, since I'm only writting stuff here, I couldn't care less about this "bug" ;-).
When you get an error in the plugin, the message shown is:
error occured in check plugin. Please post a issue on inlcuding the output of the agent plugin /usr/lib/check_mk_agent/plugins/urbackup-check

With a link leading here. Unfortunately the link is wrong:
https://github.com/edvler/check_mk_urbackup-check/issues

**Comment by edvler** [comment]
Fixed with v1.2.0
