### ISSUE TITLE
make agent appear in check_mk to be able to download it

### ISSUE THREAD

**Issue by yennor** [edvler/check_mk-urbackup-check#4]
each time I want to install the agent on a new server, I need to find it again on github, find the raw link, etc. 
It would be very nice if the agent would be listed in check mk under agents. I guess it works for windows and linux, so maybe in both? or in other operating systems?
Like that I could get it easily with wget, and don't need to search for it again, and again...

Anyway, thanks for your plugin :-).

**Comment by edvler** [comment]
I've asked in the check_mk forum.
It's not implemented in check_mk to display custom plugins.

https://forum.checkmk.com/t/agent-plugin-not-displayed-in-web-gui/40101
